(library
 (name rocqformat_lib)
 (public_name rocqformat.lib)
 (modules rocqformat_lib rocqformat_args rocqformat_layout)
 (libraries rocq-runtime.toplevel rocq-runtime.coqargs rocq-runtime.sysinit))

(executable
 (name main)
 (public_name rocqformat)
 (package rocqformat)
 (modules main)
 (libraries rocqformat_lib))

(install
 (section libexec)
 (package rocqformat)
 (files (main.exe as rocqformat)))
